FROM centos:7

RUN mkdir -p /opt/ping_monitor_sw

COPY CentOS7_bin/ping_monitor /opt/ping_monitor_sw/ping_monitor
RUN chmod +x /opt/ping_monitor_sw/ping_monitor

COPY ping_monitor_in_docker/hosts.txt /opt/ping_monitor_sw/hosts.txt

RUN yum install  -y yum-utils
RUN yum-config-manager --enable
RUN yum update -y
RUN yum install httpd httpd-tools python rrdtool python-rrdtool gcc rrdtool-devel python-devel python-jinja2 -y

RUN yum -y install epel-release && yum clean all
RUN yum -y install python-pip && yum clean all

RUN pip install pyping rrdtool

EXPOSE 80

WORKDIR /opt/ping_monitor_sw

CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
CMD [ "./ping_monitor" ]
