FROM centos:7

WORKDIR /opt/ping_monitor_sw

COPY CentOS7_bin/ping_monitor .
RUN chmod +x /opt/ping_monitor_sw/ping_monitor

COPY ping_monitor_in_docker/hosts.txt .

RUN yum install  -y yum-utils
RUN yum-config-manager --enable
RUN yum update -y
RUN yum install httpd httpd-tools python rrdtool python-rrdtool gcc rrdtool-devel python-devel python-jinja2 -y

RUN yum -y install epel-release && yum clean all
RUN yum -y install python-pip && yum clean all

RUN pip install pyping rrdtool

EXPOSE 80

CMD ["/bin/sh", "-c", "trap : TERM INT; /usr/sbin/httpd -D FOREGROUND & (while true; do ./ping_monitor; done) & wait"]
